controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    head_controller:
      type: position_controllers/JointGroupPositionController

    gripper_controller:
      type: position_controllers/JointGroupPositionController

head_controller:
  ros__parameters:
    joints:
    - head_swivel
    interface_name: position

gripper_controller:
  ros__parameters:
    joints:
    - gripper_extension
    - left_gripper_joint
    - right_gripper_joint
    interface_name: position
